### ISSUE TITLE
cant download tenserrt model

### ISSUE THREAD

**Issue by blankplane** [nv-tlabs/DiffusionTexturePainting#2]
Initializing TensorRT Plugins
Exporting model: /workspace/onnx/vae_encoder_inpaint.onnx
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/vae/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/modeling_utils.py", line 797, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66d14301-7d56688803497ae31d227044;c79cdbaa-4c26-4950-9dea-80e3faa6e1e1)

Repository Not Found for url: https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/vae/diffusion_pytorch_model.bin.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 59, in <module>
    run_main()
  File "run.py", line 53, in run_main
    server = create_server(debug_dir=args.debug_dir)
  File "run.py", line 30, in create_server
    model = TRTConditionalInpainter(256)
  File "/workspace/trt_model.py", line 49, in __init__
    self.pipeline.loadEngines(engine_dir, onnx_dir, 16,
  File "/workspace/stable_diffusion_pipeline.py", line 271, in loadEngines
    model = obj.get_model()
  File "/workspace/models.py", line 1340, in get_model
    vae_encoder = TorchVAEEncoder(self.hf_token, self.device, self.path)
  File "/workspace/models.py", line 1332, in __init__
    self.vae_encoder = AutoencoderKL.from_pretrained(self.path, subfolder="vae", use_auth_token=token).to(device)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/modeling_utils.py", line 506, in from_pretrained
    model_file = _get_model_file(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/modeling_utils.py", line 813, in _get_model_file
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-inpainting is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

**Comment by anita-hu** [comment]
Hi, looks like runwayml took down their model weights very recently. Looking into alternative options

**Comment by anita-hu** [comment]
I have updated the readme with instructions on how to use alternative options https://github.com/nv-tlabs/DiffusionTexturePainting?tab=readme-ov-file#2-tensorrt-model-inference
I have verified that everything still works with https://huggingface.co/benjamin-paine/stable-diffusion-v1-5-inpainting
